config/routes.rb
JqmApplication::Application.routes.draw do
  root :to => "projects#index"
  match "/project_show" => "projects#project_show",:as=>"project_show"

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :end_date, :name, :start_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  respond_to :json, :html
  def index
    @projects = Project.all
    respond_to do |format|
      format.html
      format.json {render :json => {:projects => @projects }}
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    respond_with(@project)
  end

  def project_show
    render :file => "projects/show"
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    respond_with(@project)
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    respond_with(@project)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def render_javascript
		javascript_include_tag javascript_to_render
	end

	def javascript_to_render
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def alert_path(id)
		project_show_path
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JqmApplication</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>
	<%= yield %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div data-role="page" data-theme="c">
  <div data-role="header" id="projects_header">
  </div>

  <div data-role="content" data-theme=c> 
    <ul data-role="listview" id="projects_index">
    </ul>
  </div>
</div>

<script id="mheader" type="text/template">
  <h1> {{header}} </h1>
</script> 

<script id="mlistview" type="text/template">
  {{#projects}}
    <li><a href="/project_show" data-id={{id}}>{{name}}</a></li>
  {{/projects}}  
</script>

<script type="text/javascript">
  PMS.projects.index({title: "My Projects"},"/projects.json")
  $("a").live("click",function() {
    console.log("There");
    console.log(this)
    console.log($(this).data("id"));
    window.DataId = $(this).data("id");
  })
</script>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div data-role="page" data-theme="c" >
  <div data-role="header" id="projects_header">
     <h1> Show Page </h1>
  </div>
  <div data-role="content" data-theme="c" id="alert_index"> 
    <ul data-role="listview" data-filter="true" id="project_show">
    </ul>
  </div> 

  <script type="text/template" id="mproject_show">
  <li>
    <img src= '/assets/glyphicons_064_lightbulb.png' class="ui-li-icon alert-icon"/>
    <a href="#" >    
      <div class="alert-title">{{ name }}</div>  
      <div class="alert-trend">{{ description }}</div>
      <div class="alert-value">{{ start_date}} - {{ end_date }}</div>
    </a>    
  </li>
</script>


<script type="text/javascript">
  PMS.projects.show(window.DataId);
</script>     
</div>  